# Generated by Django 3.2 on 2021-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_fruit',
            field=models.IntegerField(default=0),
        ),
    ]
