# Generated by Django 3.2 on 2021-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apples', models.IntegerField(default=0)),
                ('pears', models.IntegerField(default=0)),
                ('peaches', models.IntegerField(default=0)),
            ],
        ),
    ]
