# Generated by Django 3.2 on 2021-05-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='got_apples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='got_peaches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='got_pears',
            field=models.IntegerField(default=0),
        ),
    ]
