# Generated by Django 3.2 on 2021-05-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210501_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='miniRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField(default=-1)),
                ('fruit', models.CharField(max_length=5)),
                ('quantity', models.IntegerField(default=-1)),
            ],
        ),
    ]
