# Generated by Django 3.2 on 2021-05-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_miniround'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniround',
            name='o_id',
            field=models.IntegerField(default=-1),
        ),
    ]
